# -*- coding: utf-8 -*-
"""Predictor-Universal_Regressor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FE-_eJENYhRfMSHpoJA-qJDxZBwSFH1k
"""

# Import Libraries
import streamlit as st
import numpy as np
import pandas as pd
from PIL import Image, ImageOps # Image processing
import pickle
import sklearn

# Create a file named "input.csv" and place it in the same folder as the regressor model and the code to make predictions
input = pd.read_csv('input.csv')

regressor = pickle.load(open('regressor.pkl', 'rb'))
 
# Apply model to make predictions
prediction = regressor.predict(input)
prediction_proba = regressor.predict_proba(input)